### ISSUE TITLE
Overriding some actions wont work...

### ISSUE THREAD

**Issue by JoseConseco** [huynle/ogpt.nvim#11]
In my actions I have overriden "optimize_code" ( to make it clear in template I told it to upperacase var names).
It worked ok.
Now same thing with "edit_code_with_instructions" would not work. - as u can see below  ogpt is complaining about wrong model (even though I overrode it to deepseek, and in prompt I told it to uppercase var names too )
![image](https://github.com/huynle/ogpt.nvim/assets/13521338/d18a4853-af6a-450f-b69d-5225cd5abcc3)

Now if I change tamplate name to  `edit_code_with_instructions**_mine**` , then it works ok.
Looks like some templates cant be overridden correctly.

**Comment by JoseConseco** [comment]
just to be clear both actions:
![image](https://github.com/huynle/ogpt.nvim/assets/13521338/2825a78b-015b-4821-8cd9-1d780569defd)

The are basicallly same, only template is different. Thus I think its bug in ogpt.

**Comment by huynle** [comment]
how did you set your actions in your neovim config? did you use the `action_paths` where it takes json files, or did you directly added to the `actions` portion of your config?

Most likely, you are using the `action_paths` since the screenshot looks like they are from a json file. If you use the json files to set your actions, these actions are loaded, and then GETS OVERLOADED by the actions that are in your default configuration table that you initialize OGPT with.

so "edit_code_with_instructions" that you provide in your json action file, gets override by this [default "edit_code_with_instructions" action] (https://github.com/huynle/ogpt.nvim/blob/277bcccfbcb7f896d43de698609266845458e196/lua/ogpt/config.lua#L209C1-L221C9) in this [line] (https://github.com/huynle/ogpt.nvim/blob/277bcccfbcb7f896d43de698609266845458e196/lua/ogpt/flows/actions/init.lua#L48)

**Comment by JoseConseco** [comment]
ah, ok I see  - the readme links to  this 'shorter' [config](https://github.com/huynle/ogpt.nvim/blob/81b5e189a044cb9c035b0e9b5e1ad0f2e03c440a/lua/ogpt/config.lua#L10-L157)
But [your link](https://github.com/huynle/ogpt.nvim/blob/277bcccfbcb7f896d43de698609266845458e196/lua/ogpt/config.lua#L209C1-L221C9) - is slightly different (100 more lines) and indeed contains actions with "edit_code_with_instructions"

So even if I have no actions defined, they are loaded from default config, and  'actions_path' wont override it. 

May I suggest that depending on the order of defined actions, next one should override previous one? 

`default_actions = {..}  - we should be able to override it from user config`
Then user config:
```
actions = {..}  
actions_path = {..}  - last one overrides the previous ones.
```

But if users chagnes order of last two 
```
actions_path = {..} 
actions = {..}   - now this will override both default actions and actions_path  (and defaults) .

```

**Comment by huynle** [comment]
i think your issue should be solved with this MR - https://github.com/huynle/ogpt.nvim/pull/14

**Comment by huynle** [comment]
https://github.com/huynle/ogpt.nvim/pull/14

**Comment by JoseConseco** [comment]
well, right now ollama wont even start (tried to enable debug, but I got no errors). I updated my config with:
![image](https://github.com/huynle/ogpt.nvim/assets/13521338/2b2d11e6-e041-4876-832a-9c83ee02b6cf)
maybe it is wrong?

**Comment by huynle** [comment]
hrm , try it without the ending "/" in your api_host

**Comment by JoseConseco** [comment]
Ok, this worked. Now the OGPT is complaining about model not being there - but I think the issue is with parsing its name  the part after  `-` seems ingnored:
![image](https://github.com/huynle/ogpt.nvim/assets/13521338/a45a40f4-9a91-4d6f-9013-f278297d7cfe)

**Comment by huynle** [comment]
youre original model name, should still work with this new update. did you get it to work?

**Comment by JoseConseco** [comment]
Yes, the chat worked when using :OGPT . It is only when I use OGPTRun - it is complaining about wrong model .

:OGPT  - ok
![image](https://github.com/huynle/ogpt.nvim/assets/13521338/ab89abe0-5236-4ac3-a78f-925e02d73090)

:OGPTRun - wont parse model correctly (I think) . Config:
![image](https://github.com/huynle/ogpt.nvim/assets/13521338/04612b70-7581-485c-b0c4-3ff450e5743a)

I have no idea which config is executed now  -  default, my_config.actions, or  actions.json.
