### ISSUE TITLE
Error on accepting output of "edit"

### ISSUE THREAD

**Issue by zsmatrix62** [huynle/ogpt.nvim#18]
Hello,

I encounters today the error of below when hitting c-y to accept output of edit.

<img width="1456" alt="图片" src="https://github.com/huynle/ogpt.nvim/assets/2951879/fb8220b1-ee9d-4593-8937-8cccca3a3247">

E5108: Error executing lua: ...vim/lazy/ogpt.nvim/lua/ogpt/flows/actions/edits/init.lua:225: Expected Lua number
stack traceback:
        [C]: in function 'nvim_buf_set_text'
        ...vim/lazy/ogpt.nvim/lua/ogpt/flows/actions/edits/init.lua:225: in function <...vim/lazy/ogpt.nvim/lua/ogpt/flows/actions/edits/init.lua:222>

**Comment by huynle** [comment]
Try pulling master and rerun, there was a huge merge from the dev branch today. Hopefully this is fixed in that merge, if not please post again

**Comment by zsmatrix62** [comment]
i just tried pulling the main brancn and the same error exists:

<img width="1694" alt="图片" src="https://github.com/huynle/ogpt.nvim/assets/2951879/f28f7eb2-e208-4bca-b41d-ea0b8708b223">

**Comment by huynle** [comment]
i just fixed the issue, thank you for reporting it! try pulling main branch again!

**Comment by huynle** [comment]
https://github.com/huynle/ogpt.nvim/pull/20

**Comment by zsmatrix62** [comment]
> #20

Thank you !

**Comment by zsmatrix62** [comment]
Hi,

i found today maybe the same error of using default `docstring` action, with type = popup, strategy = edit:

<img width="1649" alt="图片" src="https://github.com/huynle/ogpt.nvim/assets/2951879/62059759-0602-48f4-afb8-b5511e413d8b">
