### ISSUE TITLE
Model Picker Does Not Populate

### ISSUE THREAD

**Issue by a-priestley** [huynle/ogpt.nvim#26]
When attempting to switch models in the telescope parameters window the following warning appears: 
`ogpt.nvim/lua/ogpt/models.lua:57: attempt to call field 'unpack' (a nil value)`
The model picker window appears afterward but fails to populate.

I can comment the referenced line, ignoring request headers and the model picker will populate after this error appears:
`telescope-fzf-native.nvim/lua/telescope/_extensions/fzf.lua:97: bad argument #1 to 'get_score' (cannot convert 'number' to 'const char *')`
Probably unrelated and could depend on the configured telescope fuzzyfinder, and if so I can open a separate issue in that telescope extension tracker.

Thanks for the great plugin!

**Comment by huynle** [comment]
which provider are you using?

**Comment by a-priestley** [comment]
ollama, openai, and anthropic atm.
I discovered a few additional  things after submitting this issue: 

1. Anthropic doesn't have an endpoint in their API for listing models (that I can see).
2. OpenAI's models endpoint does not return the expected payload with a list of models called "model" -- the list provided is named "data".
3. I resolved the first error by adapting your method of populating the curl arguments in [api.lua](https://github.com/huynle/ogpt.nvim/blob/44b31d9a2d636ed8338ea6eaf1a9fc78e14314ed/lua/ogpt/api.lua) instead of `table.unpack`:
```lua
local curl_args = {
  provider:models_url(),
}
for _, header_item in ipairs(provider:request_headers()) do
  table.insert(curl_args, header_item)
end
...
:new({
  command = "curl",
  args = curl_args
...
```
4. The second error seems to be caused by [this line](https://github.com/huynle/ogpt.nvim/blob/44b31d9a2d636ed8338ea6eaf1a9fc78e14314ed/lua/ogpt/models.lua#L84), and commenting it out doesn't prevent the picker from being populated with these entries. Maybe it is causing duplicates?

**Comment by a-priestley** [comment]
[diff](https://github.com/huynle/ogpt.nvim/compare/main...a-priestley:ogpt.nvim:main)

**Comment by huynle** [comment]
thanks for the report here! i think the issue should be fixed with the latest merge to main. Please reopen the issue if you have a problem

**Comment by huynle** [comment]
https://github.com/huynle/ogpt.nvim/pull/28

**Comment by a-priestley** [comment]
No problems so far, thanks!
I guess the requirement here for anthropic is, if and until they add a models endpoint, we'll have to manually add the one's we'd like to use as local definitions?

**Comment by huynle** [comment]
exactly, and when they do provide a url for us to pull models, you can help track that and add that in!
