### ISSUE TITLE
Feature request: add mistral and openrouter backends

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [huynle/ogpt.nvim#35]

**Comment by huynle** [comment]
OpenRouter seems really interesting! i havent' had a chance to play with it. but it should not be too hard to get it added as an other provider. I'm a little busy at the moment with work/life. Does anyone here want to take a stab at this?

**Comment by huynle** [comment]
added here - https://github.com/huynle/ogpt.nvim/pull/41/
