### ISSUE TITLE
Cant change default model?

### ISSUE THREAD

**Issue by JoseConseco** [huynle/ogpt.nvim#9]
Hi, here is my config where I chagned default models:
![image](https://github.com/huynle/ogpt.nvim/assets/13521338/6fc16bd9-43ff-4997-a29a-ac72d50b05e1)

but it is still calling mistral by default. Not sure if this is bug, or I'm missing somehting

**Comment by huynle** [comment]
if your "actions" are still using `mistral` you might have `params.model` defined as `mistral` for the given action:
<img width="499" alt="image" src="https://github.com/huynle/ogpt.nvim/assets/2416122/1f08cf49-f0ee-404d-8c24-08e9190962f0">

**Comment by JoseConseco** [comment]
Thanks, indeed that was issue.  Btw. now I'm not sure what is wrong but when I try to use 'optimize code' action, the selected code is  pasted in left  window, but it is not wrapped into action template:
![image](https://github.com/huynle/ogpt.nvim/assets/13521338/6265b887-93d9-4ccd-8b1e-b463d2413b7e)

and  model is doing nothing (I assume it should start outputting optimized code right  away...) 

I can ask it for optimization, but then is  behaves like it did not see the selected code at all:
![image](https://github.com/huynle/ogpt.nvim/assets/13521338/1bf4a667-b015-4c14-86b3-0ab6759ef564)

Code explain seems to work ok. I can only assume   "edit" strategy actions types, are messed up..

**Comment by huynle** [comment]
this MR should fix it for you, https://github.com/huynle/ogpt.nvim/pull/10.

This updates allows us to use the template, and the `{{instruction}}`. If you leave `extract_codeblock` to true, it will stream back the result, and UPON completion, it woulld exytract out the codeblock and replace the response with it. This is useful for running a diff on the generated code and the original code.


```lua
-- content under config.lua

      -- all strategy "edit" have instruction as input
      edit_code_with_instructions = {
        type = "chat",
        opts = {
          strategy = "edit_code",
          template = "Given the follow code snippet, {{instruction}}.\n\nCode:\n```{{filetype}}\n{{input}}\n```",
          delay = true,
          extract_codeblock = true,
          params = {
            model = "deepseek-coder:6.7b",
          },
        },
      },

      -- all strategy "edit" have instruction as input
      edit_with_instructions = {
        type = "chat",
        opts = {
          strategy = "edit",
          template = "Given the follow snippet, {{instruction}}.\n\nSnippet:\n```{{filetype}}\n{{input}}\n```",
          delay = true,
          params = {
            model = "mistral:7b",
          },
        },
      },
    },
```

**Comment by JoseConseco** [comment]
Thanks. Seems to work ok now.  awesome work on the plugin.
